// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package flow

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadConnect returns the embedded CollectionSpec for Connect.
func LoadConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Connect: %w", err)
	}

	return spec, err
}

// LoadConnectObjects loads Connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ConnectObjects
//	*ConnectPrograms
//	*ConnectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadConnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ConnectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectSpecs struct {
	ConnectProgramSpecs
	ConnectMapSpecs
}

// ConnectSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectProgramSpecs struct {
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
}

// ConnectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ConnectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectObjects struct {
	ConnectPrograms
	ConnectMaps
}

func (o *ConnectObjects) Close() error {
	return _ConnectClose(
		&o.ConnectPrograms,
		&o.ConnectMaps,
	)
}

// ConnectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ConnectMaps) Close() error {
	return _ConnectClose(
		m.Events,
	)
}

// ConnectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectPrograms struct {
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
}

func (p *ConnectPrograms) Close() error {
	return _ConnectClose(
		p.TraceConnect,
	)
}

func _ConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_x86_bpfel.o
var _ConnectBytes []byte
